# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1162, 510)
        MainWindow.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1141, 861))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 260, 150))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border:2px solid black;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:4px;\n"
"color: rgb(210, 252, 0);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("photo/New Project.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(125, 125))
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 180, 260, 150))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("border:2px solid black;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:4px;\n"
"color: rgb(210, 252, 0);")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("photo/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(125, 125))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 350, 260, 150))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("border:2px solid black;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:4px;\n"
"color: rgb(210, 252, 0);")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("photo/history-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(125, 125))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(310, 10, 851, 751))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("border-style:none none none none;")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 71, 40))
        self.label_2.setStyleSheet("border:2px solid black;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius:4px;\n"
"color: rgb(210, 252, 0);")
        self.label_2.setObjectName("label_2")
        self.urlText = QtWidgets.QLineEdit(self.tab_1)
        self.urlText.setGeometry(QtCore.QRect(110, 10, 711, 40))
        self.urlText.setStyleSheet("border:2px solid black;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius:4px;\n"
"color: rgb(210, 252, 0);")
        self.urlText.setText("")
        self.urlText.setObjectName("urlText")
        self.download = QtWidgets.QPushButton(self.tab_1)
        self.download.setGeometry(QtCore.QRect(30, 100, 791, 100))
        self.download.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.download.setStyleSheet("border:2px solid black;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius:4px;\n"
"color: rgb(210, 252, 0);")
        self.download.setObjectName("download")
        self.progressBar = QtWidgets.QProgressBar(self.tab_1)
        self.progressBar.setGeometry(QtCore.QRect(30, 60, 791, 31))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"     border: 2px solid black;\n"
"     border-radius: 4px;\n"
" \n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: rgb(210, 252, 0);\n"
"     border-radius:4px;\n"
"     width: 20px;\n"
" }")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pathLabel = QtWidgets.QLabel(self.tab_2)
        self.pathLabel.setGeometry(QtCore.QRect(30, 10, 70, 40))
        self.pathLabel.setStyleSheet("border:2px solid black;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius:4px;\n"
"color: rgb(210, 252, 0);")
        self.pathLabel.setObjectName("pathLabel")
        self.pathField = QtWidgets.QLineEdit(self.tab_2)
        self.pathField.setGeometry(QtCore.QRect(110, 10, 711, 40))
        self.pathField.setStyleSheet("border:2px solid black;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius:4px;\n"
"color: rgb(210, 252, 0);")
        self.pathField.setText("")
        self.pathField.setReadOnly(True)
        self.pathField.setObjectName("pathField")
        self.path_button = QtWidgets.QPushButton(self.tab_2)
        self.path_button.setGeometry(QtCore.QRect(30, 60, 791, 41))
        self.path_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.path_button.setStyleSheet("border:2px solid black;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius:4px;\n"
"color: rgb(210, 252, 0);")
        self.path_button.setObjectName("path_button")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 831, 471))
        self.tableWidget.setStyleSheet("QHeaderView::section {\n"
"\n"
"border:2px solid black;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius:4px;\n"
"color: rgb(210, 252, 0);\n"
"background-color: rgb(35, 35, 35);\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"background-color: rgb(35, 35, 35);\n"
"}\n"
"\n"
"QTableView::item {\n"
"\n"
"color: rgb(210, 252, 0);\n"
"qproperty-defaultAlignment: AlignVCenter;\n"
"background-color: black;\n"
"border:1px solid #D2FC00;\n"
"border-style:none solid solid none;\n"
"}\n"
"\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "  URL"))
        self.download.setText(_translate("MainWindow", "Download"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Tab 1"))
        self.pathLabel.setText(_translate("MainWindow", "PATH"))
        self.path_button.setText(_translate("MainWindow", "SET PATH"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Link"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Size"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
